language: python
python:
    - 2.6
    - 2.7
    - pypy
install:
    - pip install nose
script:
    - nosetests --with-doctest --doctest-options=+IGNORE_EXCEPTION_DETAIL
notifications:
    email: false
